desc       = "A set of strings, the main package of this module."
package    = "stringset"
type       = "string"
zero       = '""'
transforms = true
toString   = "return strconv.Quote(x)"
imports    = ["strconv"]
testValues = [
  '"eight"', '"five"', '"four"', '"nine"', '"one"',
  '"seven"', '"six"', '"ten"', '"three"', '"two"'
]
